### ISSUE TITLE
timedatex commit introduced syntax error

### ISSUE THREAD

**Issue by tiran** [wrabcak/selinux-policy-contrib#142]
Commit 7a76bedbdf4a518c4dcc4f6e01968929e3234428 introduced a syntax error:

```
policy/modules/contrib/timedatex.te:30:ERROR 'syntax error' at token 'systemd_timedated_status' on line 3259:
systemd_timedated_status(timedatex_t)
```

**Comment by wrabcak** [comment]
@tiran, 
I tried to build selinux policy for F31 and Rawhide and it's working for me, could you try it one more time?

**Comment by tiran** [comment]
Ah, could it be related to the fact that I'm trying to build the policy for F31 on a F29 system? Perhaps it's necessary to raise the version number of dependencies.

**Comment by wrabcak** [comment]
yes, that could be the case for sure.
